src/config/urls.py
from django.contrib import admin
from django.urls import include, path

from core import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("saludar/", views.saludar),
    path("saludar-con-etiquetas/", views.saludar_con_etiqueta),
    path("dados/", views.tirar_dado),
    path("notas/", views.notas),
    path("", include("core.urls")),
    path("producto/", include("producto.urls")),
]

src/core/urls.py
from django.urls import path

from core import views

app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
]

src/producto/urls.py
from django.urls import path

from producto import views

app_name = "producto"

urlpatterns = [
    # path("lista/", views.categoria_list, name="lista"),
    # path("crear/", views.categoria_create, name="crear"),
    # path("cambiar/<int:pk>", views.categoria_update, name="cambiar"),
    # path("detalle/<int:pk>", views.categoria_detail, name="detalle"),
    # path("borrar/<int:pk>", views.categoria_delete, name="borrar"),
    path("cambiar/<int:pk>", views.CategoriaUpdate.as_view(), name="cambiar"),
    path("lista/", views.CategoriaList.as_view(), name="lista"),
    path("crear/", views.CategoriaCreate.as_view(), name="crear"),
    path("detalle/<int:pk>", views.CategoriaDetail.as_view(), name="detalle"),
    path("borrar/<int:pk>", views.CategoriaDelete.as_view(), name="borrar"),
]

src/core/models.py
from django.db import models

# Create your models here.

src/producto/models.py
from django.db import models


class Categoria(models.Model):
    nombre = models.CharField(max_length=250, unique=True)
    descripcion = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.nombre}"

src/producto/forms.py
from django import forms

from .models import Categoria


class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        # fields = ["nombre", "descripcion"]
        fields = "__all__"

src/core/views.py
from django.http import HttpResponse
from django.shortcuts import render


def saludar(request):
    return HttpResponse("Hola desde Django!")


def saludar_con_etiqueta(request):
    return HttpResponse("<h1>Uso de etiquetas HTML</h1>")


def index(request):
    return render(request, "core/index.html", {"titulo": "Python - Django"})


def tirar_dado(request):
    from datetime import datetime
    from random import randint

    tiro_de_dado = randint(1, 6)
    if tiro_de_dado == 6:
        mensaje = f"Has tirado el 🎲 y has obtenido {tiro_de_dado}, 🥂 GANASTE!"
    else:
        mensaje = f"Has tirado el 🎲 y has obtenido {tiro_de_dado}, 🙁 PERDISTE!"
    datos = {
        "titulo": "Tiro de Dados",
        "mensaje": mensaje,
        "fecha": datetime.now().strftime("%d/%m/%Y %H:%M:%S"),
    }
    return render(request, "core/tirar_dado.html", datos)


def notas(request):
    mis_notas = [10, 7, 4, 6, 8, 8]
    return render(request, "core/notas.html", context={"notas": mis_notas})

src/producto/views.py
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView

from . import models
from . import forms


# def categoria_list(request):
#     consulta = request.GET.get("consulta")
#     if consulta:
#         categorias = models.Categoria.objects.filter(nombre__contains=consulta)
#     else:
#         categorias = models.Categoria.objects.all()
#     return render(request, "producto/categoria_list.html", {"categorias": categorias})

class CategoriaList(ListView):
    model = models.Categoria
    # template_name = "producto/categoria_list.html"
    # context_object_name = "categorias"

    def get_queryset(self):
        consulta = self.request.GET.get("consulta")
        if consulta:
            categorias = models.Categoria.objects.filter(nombre__contains=consulta)
        else:
            categorias = models.Categoria.objects.all()
        return categorias



# def categoria_detail(request, pk: int):
#     categoria = models.Categoria.objects.get(id=pk)
#     return render(request, "producto/categoria_detail.html", {"categoria": categoria})

class CategoriaDetail(DetailView):
    model = models.Categoria


# def categoria_delete(request, pk: int):
#     categoria = models.Categoria.objects.get(id=pk)
#     if request.method == "POST":
#         categoria.delete()
#         return redirect("producto:lista")
#     contexto = {"categoria": categoria}
#     return render(request, "producto/categoria_confirm_delete.html", contexto)

class CategoriaDelete(DeleteView):
    model = models.Categoria
    success_url = reverse_lazy("producto:lista")

# def categoria_create(request):
#     if request.method == "POST":
#         form = forms.CategoriaForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect("producto:lista")
#     else:
#         form = forms.CategoriaForm()
   
#     return render(request, "producto/categoria_create.html", {"form": form})

class CategoriaCreate(CreateView):
    model = models.Categoria
    form_class = forms.CategoriaForm
    success_url = reverse_lazy("producto:lista")


# def categoria_update(request, pk: int):
#     categoria = models.Categoria.objects.get(id=pk)
#     if request.method == "GET":
#         form = forms.CategoriaForm(instance=categoria)
#     if request.method == "POST":
#         form = forms.CategoriaForm(request.POST, instance=categoria)
#         if form.is_valid():
#             form.save()
#             return redirect("producto:lista")
#     return render(request, "producto/categoria_form.html", {"form": form})


class CategoriaUpdate(UpdateView):
    model = models.Categoria
    form_class = forms.CategoriaForm
    success_url = reverse_lazy("producto:lista")

src/core/templates/core/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Coderhouse</title>
</head>
<body style="margin: 2%;">
    <header>
        <h1 style="text-align: center;">
          
            {% block titulo %}
            {% endblock titulo %}

        </h1>
    </header>
    {% include 'core/componentes/navbar.html' %}
    <main>
        {% block main %}
        {% endblock main %}
    </main>
    {% include 'core/componentes/footer.html' %}
</body>
</html>

src/core/templates/core/componentes/footer.html
<footer>
    <p>Hecho por nosotros</p>
</footer>

src/core/templates/core/componentes/navbar.html
<nav>
    <ul>
        <li><a href="{% url 'core:index' %}">Inicio</a></li>
        <li><a href="{% url 'producto:lista' %}">Categorías</a></li>
    </ul>
</nav>

src/core/templates/core/index.html
{% extends 'core/base.html' %}

{% load static %}


{% block titulo %}
  <p>{{ titulo }}</p>
{% endblock titulo %}

{% block main %}
  <img src="{% static 'core/img/caja-pandora.jpg' %}" alt="imagen"
   width="20%" height="auto" style="display: block; margin: auto;" />
{% endblock main %}

src/core/templates/core/notas.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div style="font-size: larger; 
                color: deepskyblue; 
                text-align: center;">
        <h1>Notas</h1>
        {% for nota in notas %}
            {% if nota >= 7 %}
                <p style="color: green;">{{ nota }}</p>
            {% else %}
                <p style="color: red;">{{ nota }}</p>
            {% endif %}
        {% endfor %}
    </div>
</body>

</html>

src/core/templates/core/tirar_dado.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>{{ titulo }}</h1>
    <p>{{ mensaje }}</p>
    <footer>Hecho con Django en {{ fecha }} </footer>
</body>

</html>

src/producto/templates/producto/categoria_confirm_delete.html
{% extends 'core/base.html' %}

{% block titulo %}
    Borrar Categoría de Productos
{% endblock titulo %}

{% block main %}
    <p>¿Estás seguro de borrar la categoría "{{ categoria.nombre }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirmo</button>
    </form>
{% endblock main %}

src/producto/templates/producto/categoria_create.html
{% extends 'core/base.html' %}

{% block titulo %}
    Crear Categorías de Productos
{% endblock titulo %}


{% block main %}
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit">Guardar</button>
    </form>
{% endblock %}

src/producto/templates/producto/categoria_detail.html
{% extends 'core/base.html' %}

{% block titulo %}
    Detalle de Categoría
{% endblock titulo %}

{% block main %}
    <ul>
        <li>Nombre: {{ categoria.nombre }}</li>
        {% if categoria.descripcion %}
            <li>Descripción: {{ categoria.descripcion }}</li>
        {% else %}
            <li>Descripción: -</li>
        {% endif %}
    </ul>
{% endblock main %}

src/producto/templates/producto/categoria_form.html
{% extends 'core/base.html' %}

{% block titulo %}
    {% if form.instance.pk is not None %}
        Actualizar Categorías de Productos
    {% else %}
        Crear Categorías de Productos
    {% endif %}
{% endblock titulo %}


{% block main %}
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit">Guardar</button>
    </form>
{% endblock %}

src/producto/templates/producto/categoria_list.html
{% extends 'core/base.html' %}

{% block titulo %}
    Categorías de Productos
{% endblock titulo %}

{% block main %}
    <button><a href="{% url 'producto:crear' %}">Crear</a></button>

    <form method="get">
        <input type="text" name="consulta" placeholder="Buscar...">
        <button type="submit">Buscar</button>
    </form>


    <ul>
        {% for categoria in object_list %}
            <li>{{ categoria.nombre }} 
                <a href="{% url 'producto:detalle' categoria.id %}">Detalle</a>
                <a href="{% url 'producto:cambiar' categoria.id %}">Cambiar</a>
                <a href="{% url 'producto:borrar' categoria.id %}">Borrar</a></li>
            </li>
        {% empty %}
            <p>No hay registros</p>
        {% endfor %}
    </ul>
{% endblock main %}